name: Midhat Mujkic
favicon: null
layout_spectrum: 0.23540117358788848
typography_spectrum: 0.47821236471645534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#335e86'
    - '#100605'
    - '#d8cdb7'
    - '#5986b0'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
