title: Mido
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1042553
  brandStrength: 0.2255319
  lightness: 0.8446808
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  rhythmicContrast: 0.6709545
navigation:
  - name: mido.me
    url: 'http://mido.me'
    type: external
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Mido
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2617021
layout_spectrum: 0.7404255
