name: Mido
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30419
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mido
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192026'
    - '#b26749'
    - '#c9825e'
    - '#b8a397'
    - '#613732'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
