name: Midhat Mujkic
favicon: null
layout_spectrum: 0.74464
typography_spectrum: 0.30983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3dcf0'
    - '#100b08'
    - '#743523'
    - '#517085'
    - '#a48358'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
