name: Midhat Mujkic
favicon: null
layout_spectrum: 0.23540117358788848
typography_spectrum: 0.47821236471645534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1991578727029264
  lightness: 0.9451680311467499
  saturation: 0.28800678555853665
  rhythmicContrast: 0.7987967829685658
purpose: []
