name: Midhat Mujkic
favicon: null
layout_spectrum: 0.76631
typography_spectrum: 0.47163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#553c59'
    - '#07060c'
    - '#e83438'
    - '#e98f52'
    - '#fcfffb'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
