name: Midhat Mujkic
favicon: null
layout_spectrum: 0.76631
typography_spectrum: 0.47163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060a0d'
    - '#faf5f1'
    - '#d6bfba'
    - '#a08691'
    - '#685479'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
